IMPORTS

In [5]:
import pandas as pd
import numpy as np

In [6]:
sales = pd.read_csv("../data/cleaned/sales_details_clean.csv")

loan1 = pd.read_csv("../data/cleaned/loan_list_1_clean.csv")

loan2 = pd.read_csv("../data/cleaned/loan_list_2_clean.csv")

MASTER LOAN TABLE

In [7]:
loans = pd.concat([loan1, loan2], ignore_index=True)

print(loans.shape)

(2763, 17)

===============================
SALES ANALYSIS
===============================

TOTAL PHONES SOLD

In [8]:
print(f"Total Phones Sold : {len(sales)}")

Total Phones Sold : 215

REVENUE

In [9]:
print("Total Selling Price")

sales["sp"].sum()

Total Selling Price

np.float64(7691324.0)

TOTAL BUYING COST

In [10]:
sales["bp"].sum()

np.int64(5362400)

TOTAL PROFIT

In [11]:
sales["margin"].sum()

np.int64(2328924)

BEST SELLING MODELS

In [12]:
sales["items"].value_counts()

items
A200 4/64          173
POP 20 4/128 GB     20
POP 20 6/64 GB      16
SPARK GO 3 4/64      3
ITEL A200            2
Name: count, dtype: int64

BEST SALES AGENTS

In [13]:
sales.groupby("agent_name").agg(

Phones_Sold=("items","count"),

Revenue=("sp","sum"),

Profit=("margin","sum")

).sort_values(

"Phones_Sold",

ascending=False
)

                   Phones_Sold   Revenue  Profit
agent_name
KIVUVA CHARLES              44  793993.0  250793
WINFRED MUTUA               28  509236.0  143836
KENNEDY MULU                23  411118.0  133468
ERICK KAMAU                 16  290992.0   94192
ALICE KASIA                 16  290605.0   91305
WAWERU ANN                  15  272805.0   88305
NEHEMIAH NGIRA              14  251135.0   75335
SABETH THAMBI               11  200057.0   64757
VINCENT OTUNGA              11  194983.0   62583
SILVESTER MUSYOKA           10  171722.0   38722
HENRY OMOLLO                 9  149837.0   22087
PETER MWANGI                 8  145496.0   47096
VALENTINE  KIMANI            4   72748.0   23548
VIOLET   OCHIENG             4   72748.0   23548
LUCY MUNYI                   1   18187.0    4887

===============================
LOAN ANALYSIS
===============================

TOTAL LOANS

In [14]:
len(loans)

2763

TOTAL VALUE

In [15]:
loans["loan_amount"].sum()

np.int64(36347677)

OURSTANDING DEBT

In [16]:
loans["debt"].sum()

np.float64(1083224.0)

AVERAGE DPD

In [17]:
loans["debt"].sum()

np.float64(1083224.0)

Branch Performance

In [18]:
loans.groupby("shop").agg(

Phones=("agreement_number","count"),

Loan_Value=("loan_amount","sum"),

Debt=("debt","sum"),

Average_DPD=("dpd","mean")

).sort_values(

"Phones",

ascending=False
)

,Phones,Loan_Value,Debt,Average_DPD
shop,,,,
WHIXUS ZONE LIMITED _THIKA,1062,11404466,667351.0,7.053672
ANTONIO PHONE ACCESSORIES LTD THIKA,402,5871231,126397.0,2.587065
ANTONIO PHONE ACCESSORIES LTD KIAMBU,352,5275762,128344.0,2.673295
ANTONIO PHONE ACCESSORIES LIMITED NYERI,177,2615668,29949.0,1.819209
ANTONIO PHONE ACCESSORIES BUNGOMA,148,2151856,24250.0,1.763514
ANTONIO PHONE ACCESSORIES LTD LOWER KABETE,137,1958266,18785.0,1.474453
ANTONIO PHONE ACCESSORIES LTD KITALE BRANCH,131,1897323,26214.0,2.106870
ANTONIO PHONE ACCESSORIES MURANG'A,126,1847140,16184.0,1.428571
ANTONIO PHONE ACCESSORIES LTD MOMBASA,63,943890,10681.0,1.777778
ANTONIO PHONE ACCESSORIES LIMITED KWALE,59,846156,9847.0,1.762712
WHIXUS ZONA LIMITED KIAMBU,53,728450,17874.0,3.792453
ANTONIO PHONE ACCESSORIES LTD MALINDI,25,382261,4484.0,2.000000
ANTONIO PHONE ACCESSORIES LTD MAKONGENI,24,367800,2376.0,1.000000
ANTONIO PHONE ACCESSORIES LIMITED NANYUKI,4,57408,488.0,3.000000

Brand Performance

In [19]:
loans.groupby("brand").agg(

Phones=("agreement_number","count"),

Loan_Value=("loan_amount","sum"),

Debt=("debt","sum")

).sort_values(

"Phones",

ascending=False
)

         Phones  Loan_Value      Debt
brand
TECNO      1382    19695139  327231.0
ITEL       1168    13839047  644938.0
INFINIX     212     2796397  111055.0
OPPO          1       17094       0.0

Model Performance

In [20]:
loans["market_name"].value_counts()

market_name
POP 20          1339
A06              697
A100             405
SMART 20         136
SMART 10 4G       41
A200              39
HOT 60I           35
SPARK 50          24
POP 10            17
A90               14
CITY 200          13
CAMON 50 PRO       2
A6X                1
Name: count, dtype: int64

===============================
PAYMENT ANALYSIS
===============================

Paid within first week

In [21]:
loans["paid_less_than4_in_the_first_week"].value_counts(dropna=False)

paid_less_than4_in_the_first_week
0.0    2378
1.0     292
NaN      93
Name: count, dtype: int64

Paid within first month

In [22]:
loans["paid_less_than15_in_the_first_month"].value_counts(dropna=False)

paid_less_than15_in_the_first_month
NaN    1971
0.0     657
1.0     135
Name: count, dtype: int64

===============================
DATA QUALITY
===============================

DUPLICATE IMEI

In [23]:
loans["imei"].duplicated().sum()

np.int64(0)

DUPLICATE AGREEMENTS

In [24]:
loans["agreement_number"].duplicated().sum()

np.int64(0)

===============================
RECONCILIATION
===============================

SALES IMEIs

In [25]:
sales_imei = set(sales["serials"])

LOAN IMEIs

In [26]:
loan_imei = set(loans["imei"])

PHONES SOLD BUT NOT FINANCED

In [27]:
missing_in_loans = sales[
    ~sales["serials"].isin(loan_imei)
]

missing_in_loans

,date,company,customer_name,customer_id,customer_phone,items,serials,bp,sp,margin,agent_name,agent_phone,country,missing_customer,missing_serial,missing_agent
0,2026-07-11,ANTONIO PHONES & ACCESSORIES HUB,BENSON CHUMBA,38234909.0,710305119.0,A200 4/64,3.550550e+14,12300,18187.0,5887,KENNEDY MULU,746125146.0,KENYA,False,False,False
1,2026-07-10,ANTONIO PHONES & ACCESSORIES HUB,RUTH OWINO,329811043.0,769671832.0,A200 4/64,3.550550e+14,13300,18187.0,4887,WINFRED MUTUA,725527722.0,KENYA,False,False,False
2,2026-07-10,ANTONIO PHONES & ACCESSORIES HUB,DIANA AOKO,34075285.0,794009147.0,A200 4/64,3.550550e+14,13300,18187.0,4887,WINFRED MUTUA,725527722.0,KENYA,False,False,False
3,2026-07-10,ANTONIO PHONES & ACCESSORIES HUB,IDI ONYANGO,11486487.0,720368576.0,A200 4/64,3.550550e+14,13300,18187.0,4887,WINFRED MUTUA,725527722.0,KENYA,False,False,False
4,2026-07-10,ANTONIO PHONES & ACCESSORIES HUB,MILLY OMONDI,31778127.0,745664899.0,A200 4/64,3.550550e+14,13300,18187.0,4887,WINFRED MUTUA,725527722.0,KENYA,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,2026-07-07,ANTONIO PHONES & ACCESSORIES HUB,ROSE APIYO,30146162.0,794481684.0,A200 4/64,3.550550e+14,12300,18187.0,5887,WINFRED MUTUA,725527722.0,KENYA,False,False,False
209,2026-07-07,ANTONIO PHONES & ACCESSORIES HUB,IFI ONYANGO,11486487.0,757418006.0,A200 4/64,3.550550e+14,12300,18187.0,5887,WINFRED MUTUA,725527722.0,KENYA,False,False,False
212,2026-07-07,ANTONIO PHONES & ACCESSORIES HUB,DENNIS OTIENO,0.0,793916721.0,A200 4/64,3.550550e+14,12300,18187.0,5887,NEHEMIAH NGIRA,794112133.0,KENYA,False,False,False
213,2026-07-07,ANTONIO PHONES & ACCESSORIES HUB,EFFIE MURICHO,828199494.0,759905504.0,ITEL A200,3.550550e+14,11300,17300.0,6000,KENNEDY MULU,746125146.0,KENYA,False,False,False
214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2681200,3845662.0,1164462,NaN,NaN,NaN,True,False,True

In [28]:
missing_in_loans.to_csv(
    "../data/reports/sales_not_in_loans.csv",
    index=False,
    encoding="utf-8-sig"
)

this deserves investigations

LOANS WITHOUT SALES

In [29]:
missing_in_sales = loans[
    ~loans["imei"].isin(sales_imei)
]

missing_in_sales

,agreement_number,issuance_date,dealer,shop,agent,loan_amount,phone_price,brand,model,market_name,imei,dpd,debt,paid_less_than4_in_the_first_week,paid_less_than15_in_the_first_month,missing_debt,missing_imei
0,AG9709415,2026-07-11,ANTONIO PHONE ACCESSORIES LTD,ANTONIO PHONE ACCESSORIES LTD LOWER KABETE,BETTY MUSYOKA,13724,18800,TECNO,KN3,POP 20,351691223503260,0,NaN,NaN,NaN,True,False
1,AG1569303,2026-07-11,ANTONIO PHONE ACCESSORIES LTD,ANTONIO PHONE ACCESSORIES MURANG'A,PAMELA AOKO,13724,18800,TECNO,KN3,POP 20,351691223488736,0,NaN,NaN,NaN,True,False
2,AG0543337,2026-07-11,ANTONIO PHONE ACCESSORIES LTD,ANTONIO PHONE ACCESSORIES LIMITED NYERI,CAROLINE MUANGE,15476,21200,TECNO,KN4,SPARK 50,357089280847809,0,NaN,NaN,NaN,True,False
3,AG3919755,2026-07-11,ANTONIO PHONE ACCESSORIES LTD,ANTONIO PHONE ACCESSORIES LTD LOWER KABETE,BENJAMIN MWENDA,13724,18800,TECNO,KN3,POP 20,351691223502957,0,NaN,NaN,NaN,True,False
4,AG9300916,2026-07-11,ANTONIO PHONE ACCESSORIES LTD,ANTONIO PHONE ACCESSORIES LTD LOWER KABETE,BETTY MUSYOKA,13724,18800,TECNO,KN3,POP 20,351691223532129,0,NaN,NaN,NaN,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2758,AG6734251,2026-04-29,WHIXUS ZONA LIMITED,WHIXUS ZONE LIMITED _THIKA,PETER SAISI,10626,13800,ITEL,a6610l,A90,355960274153390,0,NaN,0.0,0.0,True,False
2759,AG8045489,2026-04-29,WHIXUS ZONA LIMITED,WHIXUS ZONE LIMITED _THIKA,JIMMY KYULE,11396,14800,INFINIX,X6725,SMART 10 4G,359724632863413,0,NaN,1.0,0.0,True,False
2760,AG1278082,2026-04-29,WHIXUS ZONA LIMITED,WHIXUS ZONE LIMITED _THIKA,JIMMY KYULE,10626,13800,ITEL,a6610l,A90,355960274316765,50,4119.0,0.0,0.0,False,False
2761,AG2891881,2026-04-29,WHIXUS ZONA LIMITED,WHIXUS ZONE LIMITED _THIKA,PETER SAISI,30646,39800,TECNO,CN5C,CAMON 50 PRO,359628311263276,0,NaN,1.0,0.0,True,False
2762,AG3481379,2026-04-29,WHIXUS ZONA LIMITED,WHIXUS ZONE LIMITED _THIKA,PETER SAISI,10626,13800,ITEL,a6610l,A90,355960274233051,0,NaN,0.0,0.0,True,False

In [30]:
missing_in_sales.to_csv(
    "../data/reports/loans_not_in_sales.csv",
    index=False,
    encoding="utf-8-sig"
)

In [31]:
missing_in_loans["issue"] = "Sale found but no matching loan record"

missing_in_sales["issue"] = "Loan found but no matching sales record"

another investigations

===============================
EXECUTIVE SUMMARY
===============================

In [32]:
summary = {

"Phones Sold":len(sales),

"Loans Issued":len(loans),

"Revenue":sales["sp"].sum(),

"Profit":sales["margin"].sum(),

"Outstanding Debt":loans["debt"].sum(),

"Average DPD":round(loans["dpd"].mean(),2),

"Sales Missing in Loans":len(missing_in_loans),

"Loans Missing in Sales":len(missing_in_sales)

}

summary

{'Phones Sold': 215,
 'Loans Issued': 2763,
 'Revenue': np.float64(7691324.0),
 'Profit': np.int64(2328924),
 'Outstanding Debt': np.float64(1083224.0),
 'Average DPD': np.float64(4.06),
 'Sales Missing in Loans': 182,
 'Loans Missing in Sales': 2730}

In [33]:
sales[["serials", "customer_phone", "agent_phone"]].head()

        serials  customer_phone  agent_phone
0  3.550550e+14     710305119.0  746125146.0
1  3.550550e+14     769671832.0  725527722.0
2  3.550550e+14     794009147.0  725527722.0
3  3.550550e+14     720368576.0  725527722.0
4  3.550550e+14     745664899.0  725527722.0

creating master table

In [34]:
master_loans = pd.concat(
    [loan1, loan2],
    ignore_index=True
)

In [35]:
master_loans.head()

,agreement_number,issuance_date,dealer,shop,agent,loan_amount,phone_price,brand,model,market_name,imei,dpd,debt,paid_less_than4_in_the_first_week,paid_less_than15_in_the_first_month,missing_debt,missing_imei
0,AG9709415,2026-07-11,ANTONIO PHONE ACCESSORIES LTD,ANTONIO PHONE ACCESSORIES LTD LOWER KABETE,BETTY MUSYOKA,13724,18800,TECNO,KN3,POP 20,351691223503260,0,NaN,NaN,NaN,True,False
1,AG1569303,2026-07-11,ANTONIO PHONE ACCESSORIES LTD,ANTONIO PHONE ACCESSORIES MURANG'A,PAMELA AOKO,13724,18800,TECNO,KN3,POP 20,351691223488736,0,NaN,NaN,NaN,True,False
2,AG0543337,2026-07-11,ANTONIO PHONE ACCESSORIES LTD,ANTONIO PHONE ACCESSORIES LIMITED NYERI,CAROLINE MUANGE,15476,21200,TECNO,KN4,SPARK 50,357089280847809,0,NaN,NaN,NaN,True,False
3,AG3919755,2026-07-11,ANTONIO PHONE ACCESSORIES LTD,ANTONIO PHONE ACCESSORIES LTD LOWER KABETE,BENJAMIN MWENDA,13724,18800,TECNO,KN3,POP 20,351691223502957,0,NaN,NaN,NaN,True,False
4,AG9300916,2026-07-11,ANTONIO PHONE ACCESSORIES LTD,ANTONIO PHONE ACCESSORIES LTD LOWER KABETE,BETTY MUSYOKA,13724,18800,TECNO,KN3,POP 20,351691223532129,0,NaN,NaN,NaN,True,False

In [36]:
master_loans.shape

(2763, 17)

saving Master

In [37]:
master_loans.to_csv(
    "../data/cleaned/master_loans.csv",
    index=False,
    encoding="utf-8-sig"
)

print("✅ Master Loan table created.")

✅ Master Loan table created.

master_loans.to_csv(
    "../data/cleaned/master_loans.csv",
    index=False,
    encoding="utf-8-sig"
)

print("✅ Master Loan table created.")

Branch Summary

In [38]:
branch_summary = (
    master_loans.groupby("shop")
    .agg(
        Phones=("agreement_number", "count"),
        Loan_Value=("loan_amount", "sum"),
        Outstanding_Debt=("debt", "sum"),
        Average_DPD=("dpd", "mean")
    )
    .reset_index()
)

branch_summary.head()

,shop,Phones,Loan_Value,Outstanding_Debt,Average_DPD
0,ANTONIO PHONE ACCESSORIES BUNGOMA,148,2151856,24250.0,1.763514
1,ANTONIO PHONE ACCESSORIES LIMITED KWALE,59,846156,9847.0,1.762712
2,ANTONIO PHONE ACCESSORIES LIMITED NANYUKI,4,57408,488.0,3.000000
3,ANTONIO PHONE ACCESSORIES LIMITED NYERI,177,2615668,29949.0,1.819209
4,ANTONIO PHONE ACCESSORIES LTD KIAMBU,352,5275762,128344.0,2.673295

In [39]:
branch_summary.to_csv(
    "../data/reports/branch_summary.csv",
    index=False
)

agent summary

In [40]:
agent_summary = (
    sales.groupby("agent_name")
    .agg(
        Phones_Sold=("items", "count"),
        Revenue=("sp", "sum"),
        Profit=("margin", "sum")
    )
    .sort_values("Phones_Sold", ascending=False)
    .reset_index()
)

agent_summary

           agent_name  Phones_Sold   Revenue  Profit
0      KIVUVA CHARLES           44  793993.0  250793
1       WINFRED MUTUA           28  509236.0  143836
2        KENNEDY MULU           23  411118.0  133468
3         ERICK KAMAU           16  290992.0   94192
4         ALICE KASIA           16  290605.0   91305
5          WAWERU ANN           15  272805.0   88305
6      NEHEMIAH NGIRA           14  251135.0   75335
7       SABETH THAMBI           11  200057.0   64757
8      VINCENT OTUNGA           11  194983.0   62583
9   SILVESTER MUSYOKA           10  171722.0   38722
10       HENRY OMOLLO            9  149837.0   22087
11       PETER MWANGI            8  145496.0   47096
12  VALENTINE  KIMANI            4   72748.0   23548
13   VIOLET   OCHIENG            4   72748.0   23548
14         LUCY MUNYI            1   18187.0    4887

In [41]:
agent_summary.to_csv(
    "../data/reports/agent_summary.csv",
    index=False,
    encoding="utf-8-sig"
)

brand summary

In [42]:
brand_summary = (
    loans.groupby("brand")
    .agg(
        Phones=("agreement_number", "count"),
        Loan_Value=("loan_amount", "sum"),
        Debt=("debt", "sum")
    )
    .sort_values("Phones", ascending=False)
    .reset_index()
)

brand_summary

     brand  Phones  Loan_Value      Debt
0    TECNO    1382    19695139  327231.0
1     ITEL    1168    13839047  644938.0
2  INFINIX     212     2796397  111055.0
3     OPPO       1       17094       0.0

In [43]:
brand_summary.to_csv(
    "../data/reports/brand_summary.csv",
    index=False,
    encoding="utf-8-sig"
)

model summary

In [44]:
model_summary = (
    loans.groupby("market_name")
    .agg(
        Phones=("agreement_number", "count"),
        Loan_Value=("loan_amount", "sum"),
        Debt=("debt", "sum")
    )
    .sort_values("Phones", ascending=False)
    .reset_index()
)

model_summary

     market_name  Phones  Loan_Value      Debt
0         POP 20    1339    19070055  302563.0
1            A06     697     6816733  476954.0
2           A100     405     6181154  128546.0
3       SMART 20     136     1827234   47822.0
4    SMART 10 4G      41      468776   42508.0
5           A200      39      511215    8178.0
6        HOT 60I      35      500387   20725.0
7       SPARK 50      24      370599   13492.0
8         POP 10      17      193193    6736.0
9            A90      14      148764   13190.0
10      CITY 200      13      181181   18070.0
11  CAMON 50 PRO       2       61292    4440.0
12           A6X       1       17094       0.0

In [45]:
model_summary.to_csv(
    "../data/reports/model_summary.csv",
    index=False,
    encoding="utf-8-sig"
)

branch summary

In [46]:
branch_summary = (
    loans.groupby("shop")
    .agg(
        Phones=("agreement_number", "count"),
        Loan_Value=("loan_amount", "sum"),
        Outstanding_Debt=("debt", "sum"),
        Average_DPD=("dpd", "mean")
    )
    .sort_values("Phones", ascending=False)
    .reset_index()
)

branch_summary

,shop,Phones,Loan_Value,Outstanding_Debt,Average_DPD
0,WHIXUS ZONE LIMITED _THIKA,1062,11404466,667351.0,7.053672
1,ANTONIO PHONE ACCESSORIES LTD THIKA,402,5871231,126397.0,2.587065
2,ANTONIO PHONE ACCESSORIES LTD KIAMBU,352,5275762,128344.0,2.673295
3,ANTONIO PHONE ACCESSORIES LIMITED NYERI,177,2615668,29949.0,1.819209
4,ANTONIO PHONE ACCESSORIES BUNGOMA,148,2151856,24250.0,1.763514
5,ANTONIO PHONE ACCESSORIES LTD LOWER KABETE,137,1958266,18785.0,1.474453
6,ANTONIO PHONE ACCESSORIES LTD KITALE BRANCH,131,1897323,26214.0,2.106870
7,ANTONIO PHONE ACCESSORIES MURANG'A,126,1847140,16184.0,1.428571
8,ANTONIO PHONE ACCESSORIES LTD MOMBASA,63,943890,10681.0,1.777778
9,ANTONIO PHONE ACCESSORIES LIMITED KWALE,59,846156,9847.0,1.762712
10,WHIXUS ZONA LIMITED KIAMBU,53,728450,17874.0,3.792453
11,ANTONIO PHONE ACCESSORIES LTD MALINDI,25,382261,4484.0,2.000000
12,ANTONIO PHONE ACCESSORIES LTD MAKONGENI,24,367800,2376.0,1.000000
13,ANTONIO PHONE ACCESSORIES LIMITED NANYUKI,4,57408,488.0,3.000000

In [47]:
branch_summary.to_csv(
    "../data/reports/branch_summary.csv",
    index=False,
    encoding="utf-8-sig"
)

executive summary

In [48]:
executive_summary = pd.DataFrame([summary])

executive_summary

,Phones Sold,Loans Issued,Revenue,Profit,Outstanding Debt,Average DPD,Sales Missing in Loans,Loans Missing in Sales
0,215,2763,7691324.0,2328924,1083224.0,4.06,182,2730

In [49]:
executive_summary.to_csv(
    "../data/reports/executive_summary.csv",
    index=False,
    encoding="utf-8-sig"
)

anlysis output

In [50]:
agent_summary.to_csv("../data/reports/agent_summary.csv", index=False)

brand_summary.to_csv("../data/reports/brand_summary.csv", index=False)

model_summary.to_csv("../data/reports/model_summary.csv", index=False)

executive_summary.to_csv("../data/reports/executive_summary.csv", index=False)